import React, { useState } from 'react';
import { SafeAreaView, Text, View, TouchableOpacity, TextInput, ScrollView } from 'react-native';

type Screen = 'home' | 'login' | 'register' | 'dashboard' | 'admin' | 'courts' | 'reservations' | 'matches' | 'wallet';
const API_URL = process.env.EXPO_PUBLIC_API_URL || 'http://localhost:8000';
const styles = { page: { flex: 1, backgroundColor: '#0f172a' }, container: { flexGrow: 1, justifyContent: 'center' as const, alignItems: 'center' as const, padding: 24 }, card: { width: '100%' as const, maxWidth: 720, backgroundColor: '#111827', borderRadius: 20, padding: 24, borderWidth: 1, borderColor: '#1f2937' }, title: { fontSize: 30, fontWeight: 'bold' as const, color: '#fff', marginBottom: 10, textAlign: 'center' as const }, subtitle: { fontSize: 16, color: '#cbd5e1', textAlign: 'center' as const, marginBottom: 18, marginTop: 14 }, input: { backgroundColor: '#020617', borderColor: '#334155', borderWidth: 1, color: '#fff', padding: 14, borderRadius: 10, marginBottom: 12 }, primaryButton: { backgroundColor: '#22c55e', paddingVertical: 14, paddingHorizontal: 24, borderRadius: 10, marginTop: 8 }, secondaryButton: { backgroundColor: '#334155', paddingVertical: 14, paddingHorizontal: 24, borderRadius: 10, marginTop: 10 }, moduleButton: { backgroundColor: '#1e293b', padding: 16, borderRadius: 12, marginTop: 10, borderWidth: 1, borderColor: '#334155' }, buttonText: { color: '#fff', fontWeight: 'bold' as const, fontSize: 16, textAlign: 'center' as const }, moduleTitle: { color: '#fff', fontWeight: 'bold' as const, fontSize: 17 }, moduleText: { color: '#cbd5e1', fontSize: 14, marginTop: 4 }, muted: { color: '#94a3b8', fontSize: 14, textAlign: 'center' as const, marginTop: 14 }, status: { color: '#fde68a', fontSize: 14, textAlign: 'center' as const, marginTop: 14 } };

export default function App() {
  const [screen, setScreen] = useState<Screen>('home'); const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [message, setMessage] = useState(''); const [token, setToken] = useState(''); const [result, setResult] = useState('');
  const [complexId, setComplexId] = useState(''); const [complexName, setComplexName] = useState(''); const [complexAddress, setComplexAddress] = useState(''); const [complexLat, setComplexLat] = useState('-12.0464'); const [complexLng, setComplexLng] = useState('-77.0428');
  const [courtId, setCourtId] = useState(''); const [courtName, setCourtName] = useState(''); const [courtSport, setCourtSport] = useState('futbol'); const [courtCapacity, setCourtCapacity] = useState('14'); const [courtPrice, setCourtPrice] = useState('120');
  async function checkBackend() { setMessage('Validando conexion con backend...'); try { const r = await fetch(`${API_URL}/health`); const d = await r.json(); setMessage(`Backend OK: ${d.status || 'ok'}`); } catch { setMessage('No se pudo conectar con el backend.'); } }
  async function register() { setMessage('Registrando usuario...'); try { const r = await fetch(`${API_URL}/auth/register`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ full_name: fullName, email, phone: '', role: 'player', password }) }); if (!r.ok) throw new Error(); setMessage('Usuario registrado. Ahora inicia sesion.'); setScreen('login'); } catch { setMessage('Error en registro.'); } }
  async function login() { setMessage('Iniciando sesion...'); try { const r = await fetch(`${API_URL}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ email, password }) }); if (!r.ok) throw new Error(); const d = await r.json(); setToken(d.access_token); setResult(''); setScreen('dashboard'); } catch { setMessage('No se pudo iniciar sesion.'); } }
  async function createComplex() { setResult('Creando complejo...'); try { const payload = { name: complexName, address: complexAddress, latitude: Number(complexLat), longitude: Number(complexLng) }; const r = await fetch(`${API_URL}/sports-complexes`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!r.ok) throw new Error(); const d = await r.json(); setComplexId(String(d.id)); setResult(`Complejo creado: ${d.name}. ID: ${d.id}`); } catch { setResult('No se pudo crear el complejo.'); } }
  async function updateComplex() { setResult('Actualizando complejo...'); try { if (!complexId) throw new Error(); const payload = { name: complexName, address: complexAddress, latitude: Number(complexLat), longitude: Number(complexLng) }; const r = await fetch(`${API_URL}/sports-complexes/${complexId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!r.ok) throw new Error(); const d = await r.json(); setResult(`Complejo actualizado: ${d.name}. ID: ${d.id}`); } catch { setResult('No se pudo actualizar el complejo. Verifica ID y datos.'); } }
  async function listComplexes() { setResult('Consultando complejos...'); try { const r = await fetch(`${API_URL}/sports-complexes`); const d = await r.json(); if (!Array.isArray(d) || d.length === 0) { setResult('No hay complejos registrados.'); return; } setResult(d.map((x: any) => `ID ${x.id}: ${x.name} - ${x.address} (${x.latitude}, ${x.longitude})`).join('\n')); } catch { setResult('No se pudo consultar complejos.'); } }
  async function createCourt() { setResult('Creando campo...'); try { const payload = { complex_id: complexId ? Number(complexId) : null, name: courtName, sport: courtSport, capacity: Number(courtCapacity), price_per_hour: Number(courtPrice) }; const r = await fetch(`${API_URL}/courts/`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!r.ok) throw new Error(); const d = await r.json(); setCourtId(String(d.id)); setResult(`Campo creado: ${d.name}. ID: ${d.id}`); setCourtName(''); } catch { setResult('No se pudo crear el campo.'); } }
  async function updateCourt() { setResult('Actualizando campo...'); try { if (!courtId) throw new Error(); const payload = { complex_id: complexId ? Number(complexId) : null, name: courtName, sport: courtSport, capacity: Number(courtCapacity), price_per_hour: Number(courtPrice) }; const r = await fetch(`${API_URL}/courts/${courtId}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (!r.ok) throw new Error(); const d = await r.json(); setResult(`Campo actualizado: ${d.name}. ID: ${d.id}`); } catch { setResult('No se pudo actualizar el campo. Verifica ID y datos.'); } }
  async function loadCourts() { setResult('Consultando campos...'); try { const url = complexId ? `${API_URL}/courts/?complex_id=${complexId}` : `${API_URL}/courts/`; const r = await fetch(url); const d = await r.json(); if (!Array.isArray(d) || d.length === 0) { setResult('No hay campos para el filtro seleccionado.'); return; } setResult(d.map((c: any) => `ID ${c.id}: ${c.name} - ${c.sport} - capacidad ${c.capacity} - S/ ${c.price_per_hour} - complejo ${c.complex_id || 'N/A'}`).join('\n')); } catch { setResult('No se pudo consultar campos.'); } }
  async function loadCount(path: string, label: string) { setResult(`Consultando ${label}...`); try { const r = await fetch(`${API_URL}${path}`); const d = await r.json(); setResult(`${label}: ${Array.isArray(d) ? d.length : 0} registros encontrados.`); } catch { setResult(`No se pudo consultar ${label}.`); } }
  const Back = () => <TouchableOpacity style={styles.secondaryButton} onPress={() => setScreen('dashboard')}><Text style={styles.buttonText}>Volver al panel</Text></TouchableOpacity>; let content = null;
  if (screen === 'home') content = <View style={styles.card}><Text style={styles.title}>Campo Libre</Text><Text style={styles.subtitle}>Reserva campos deportivos, convoca jugadores, registra pagos y arma equipos.</Text><TouchableOpacity style={styles.primaryButton} onPress={() => setScreen('login')}><Text style={styles.buttonText}>Iniciar sesion</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={() => setScreen('register')}><Text style={styles.buttonText}>Crear cuenta</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={checkBackend}><Text style={styles.buttonText}>Probar backend</Text></TouchableOpacity>{!!message && <Text style={styles.status}>{message}</Text>}<Text style={styles.muted}>API configurada: {API_URL}</Text></View>;
  if (screen === 'login') content = <View style={styles.card}><Text style={styles.title}>Login</Text><TextInput style={styles.input} placeholder="Email" placeholderTextColor="#64748b" value={email} onChangeText={setEmail} autoCapitalize="none" /><TextInput style={styles.input} placeholder="Password" placeholderTextColor="#64748b" value={password} onChangeText={setPassword} secureTextEntry /><TouchableOpacity style={styles.primaryButton} onPress={login}><Text style={styles.buttonText}>Entrar</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={() => setScreen('home')}><Text style={styles.buttonText}>Volver</Text></TouchableOpacity>{!!message && <Text style={styles.status}>{message}</Text>}</View>;
  if (screen === 'register') content = <View style={styles.card}><Text style={styles.title}>Crear cuenta</Text><TextInput style={styles.input} placeholder="Nombre completo" placeholderTextColor="#64748b" value={fullName} onChangeText={setFullName} /><TextInput style={styles.input} placeholder="Email" placeholderTextColor="#64748b" value={email} onChangeText={setEmail} autoCapitalize="none" /><TextInput style={styles.input} placeholder="Password" placeholderTextColor="#64748b" value={password} onChangeText={setPassword} secureTextEntry /><TouchableOpacity style={styles.primaryButton} onPress={register}><Text style={styles.buttonText}>Registrarme</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={() => setScreen('home')}><Text style={styles.buttonText}>Volver</Text></TouchableOpacity>{!!message && <Text style={styles.status}>{message}</Text>}</View>;
  if (screen === 'dashboard') content = <View style={styles.card}><Text style={styles.title}>Panel Campo Libre</Text><Text style={styles.subtitle}>Usuario normal y administrador separados por modulo.</Text><TouchableOpacity style={styles.moduleButton} onPress={() => setScreen('admin')}><Text style={styles.moduleTitle}>Administrador de complejo</Text><Text style={styles.moduleText}>Crear y actualizar complejos deportivos y campos.</Text></TouchableOpacity><TouchableOpacity style={styles.moduleButton} onPress={() => setScreen('courts')}><Text style={styles.moduleTitle}>Usuario: buscar campos</Text><Text style={styles.moduleText}>Consulta complejos y campos disponibles.</Text></TouchableOpacity><TouchableOpacity style={styles.moduleButton} onPress={() => setScreen('reservations')}><Text style={styles.moduleTitle}>Mis reservas</Text><Text style={styles.moduleText}>Revisa reservas y estados.</Text></TouchableOpacity><TouchableOpacity style={styles.moduleButton} onPress={() => setScreen('matches')}><Text style={styles.moduleTitle}>Convocatorias y sorteo</Text><Text style={styles.moduleText}>Organiza jugadores y equipos.</Text></TouchableOpacity><TouchableOpacity style={styles.moduleButton} onPress={() => setScreen('wallet')}><Text style={styles.moduleTitle}>Pagos y billetera</Text><Text style={styles.moduleText}>Controla pagos y recaudacion.</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={() => setScreen('home')}><Text style={styles.buttonText}>Cerrar sesion</Text></TouchableOpacity><Text style={styles.muted}>Token activo: {token ? `${token.substring(0, 18)}...` : 'sin token'}</Text></View>;
  if (screen === 'admin') content = <View style={styles.card}><Text style={styles.title}>Administrador</Text><Text style={styles.subtitle}>Complejo deportivo</Text><TextInput style={styles.input} placeholder="ID del complejo para actualizar" placeholderTextColor="#64748b" value={complexId} onChangeText={setComplexId} keyboardType="numeric" /><TextInput style={styles.input} placeholder="Nombre del complejo" placeholderTextColor="#64748b" value={complexName} onChangeText={setComplexName} /><TextInput style={styles.input} placeholder="Direccion" placeholderTextColor="#64748b" value={complexAddress} onChangeText={setComplexAddress} /><TextInput style={styles.input} placeholder="Latitud" placeholderTextColor="#64748b" value={complexLat} onChangeText={setComplexLat} /><TextInput style={styles.input} placeholder="Longitud" placeholderTextColor="#64748b" value={complexLng} onChangeText={setComplexLng} /><TouchableOpacity style={styles.primaryButton} onPress={createComplex}><Text style={styles.buttonText}>Crear complejo</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={updateComplex}><Text style={styles.buttonText}>Actualizar complejo</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={listComplexes}><Text style={styles.buttonText}>Listar complejos</Text></TouchableOpacity><Text style={styles.subtitle}>Campo deportivo</Text><TextInput style={styles.input} placeholder="ID del campo para actualizar" placeholderTextColor="#64748b" value={courtId} onChangeText={setCourtId} keyboardType="numeric" /><TextInput style={styles.input} placeholder="ID del complejo asociado" placeholderTextColor="#64748b" value={complexId} onChangeText={setComplexId} keyboardType="numeric" /><TextInput style={styles.input} placeholder="Nombre del campo" placeholderTextColor="#64748b" value={courtName} onChangeText={setCourtName} /><TextInput style={styles.input} placeholder="Deporte" placeholderTextColor="#64748b" value={courtSport} onChangeText={setCourtSport} /><TextInput style={styles.input} placeholder="Capacidad" placeholderTextColor="#64748b" value={courtCapacity} onChangeText={setCourtCapacity} keyboardType="numeric" /><TextInput style={styles.input} placeholder="Precio por hora" placeholderTextColor="#64748b" value={courtPrice} onChangeText={setCourtPrice} keyboardType="numeric" /><TouchableOpacity style={styles.primaryButton} onPress={createCourt}><Text style={styles.buttonText}>Crear campo</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={updateCourt}><Text style={styles.buttonText}>Actualizar campo</Text></TouchableOpacity><TouchableOpacity style={styles.secondaryButton} onPress={loadCourts}><Text style={styles.buttonText}>Listar campos</Text></TouchableOpacity>{!!result && <Text style={styles.status}>{result}</Text>}<Back /></View>;
  if (screen === 'courts') content = <View style={styles.card}><Text style={styles.title}>Buscar campos</Text><Text style={styles.subtitle}>Primero lista complejos, copia el ID y consulta sus campos.</Text><TouchableOpacity style={styles.secondaryButton} onPress={listComplexes}><Text style={styles.buttonText}>Listar complejos</Text></TouchableOpacity><TextInput style={styles.input} placeholder="ID del complejo opcional" placeholderTextColor="#64748b" value={complexId} onChangeText={setComplexId} keyboardType="numeric" /><TouchableOpacity style={styles.primaryButton} onPress={loadCourts}><Text style={styles.buttonText}>Consultar campos</Text></TouchableOpacity>{!!result && <Text style={styles.status}>{result}</Text>}<Back /></View>;
  if (screen === 'reservations') content = <View style={styles.card}><Text style={styles.title}>Mis reservas</Text><Text style={styles.subtitle}>Consulta las reservas creadas en el sistema.</Text><TouchableOpacity style={styles.primaryButton} onPress={() => loadCount('/reservations', 'Reservas')}><Text style={styles.buttonText}>Consultar reservas</Text></TouchableOpacity>{!!result && <Text style={styles.status}>{result}</Text>}<Back /></View>;
  if (screen === 'matches') content = <View style={styles.card}><Text style={styles.title}>Convocatorias</Text><Text style={styles.subtitle}>Aqui construiremos participantes, titulares, suplentes y sorteo de equipos.</Text><TouchableOpacity style={styles.primaryButton} onPress={() => setResult('Motor de sorteo pendiente de conectar.')}><Text style={styles.buttonText}>Preparar sorteo</Text></TouchableOpacity>{!!result && <Text style={styles.status}>{result}</Text>}<Back /></View>;
  if (screen === 'wallet') content = <View style={styles.card}><Text style={styles.title}>Pagos y billetera</Text><Text style={styles.subtitle}>Aqui se controlaran pagos, saldos y recaudacion.</Text><TouchableOpacity style={styles.primaryButton} onPress={() => setResult('Modulo de pagos listo para integracion.')}><Text style={styles.buttonText}>Ver estado de pagos</Text></TouchableOpacity>{!!result && <Text style={styles.status}>{result}</Text>}<Back /></View>;
  return <SafeAreaView style={styles.page}><ScrollView contentContainerStyle={styles.container}>{content}</ScrollView></SafeAreaView>;
}
